services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: security
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432"

  web:
    build: .
    command: sh -c "
      python ./backend/manage.py collectstatic --noinput &&
      python ./backend/manage.py migrate &&
      gunicorn --workers 3 --timeout 600 --chdir ./backend main.wsgi:application -b 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/public/static
      - media_volume:/app/public/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=${DEBUG}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}

volumes:
  postgres_data:
  static_volume:
  media_volume:
