# Generated by Django 5.2 on 2025-04-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_service_options_service_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('number', models.IntegerField(verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ['number'],
            },
        ),
    ]
